import { User } from "../../interfaces/dbData";

export const users: User[] = [
  {
    uid: "1",
    name: "John",
    surname: "Mayer",
    login: "JohnMayer",
    password: "passwd17654",
    email: "johnmayer@gmail.com",
    score: 1340,
    lastActivity: new Date(2022, 4, 4),
    groups: ["1", "2", "4", "5"],
    ownedGroups: ["1", "5"],
    activities: ["1", "2"],
  },
  {
    uid: "2",
    name: "Alicja",
    surname: "Keys",
    login: "AlicjaKeys",
    password: "fwswd17654",
    email: "AlicjaKeys@gmail.com",
    score: 640,
    lastActivity: new Date(2022, 2, 3),
    groups: ["1", "2"],
    ownedGroups: ["2"],
    activities: ["1", "2"],
  },
  {
    uid: "3",
    name: "Billie",
    surname: "Eilish",
    login: "BillieEilish",
    password: "fwlhdik17654",
    email: "BillieEilish@gmail.com",
    score: 100,
    lastActivity: new Date(2022, 2, 10),
    groups: ["1", "3", "4"],
    ownedGroups: ["3"],
    activities: ["3", "2", "4"],
  },
  {
    uid: "4",
    name: "Harry",
    surname: "Styles",
    login: "Harry864",
    password: "fllpjncdik176421",
    email: "BillieEilish@gmail.com",
    score: 940,
    lastActivity: new Date(2022, 4, 8),
    groups: ["1", "2", "4", "5"],
    ownedGroups: ["4"],
    activities: ["3", "2", "4"],
  },
  {
    uid: "5",
    name: "Paul",
    surname: "Hewson",
    login: "Bono123",
    password: "lrootok176421",
    email: "Bono123@gmail.com",
    score: 1540,
    lastActivity: new Date(2022, 4, 15),
    groups: ["1", "4"],
    ownedGroups: [],
    activities: ["3", "2", "4"],
  },
  {
    uid: "6",
    name: "John",
    surname: "Doe",
    login: "jo-do",
    password: "shdjdhjshjs",
    email: "johndoe@gmail.com",
    score: 2150,
    lastActivity: new Date(2022, 4, 12),
    groups: [],
    ownedGroups: [],
    activities: [],
  }];

export const user: User = users[0];
